### ISSUE TITLE
Robot is not visible in Gazebo

### ISSUE THREAD

**Issue by skapix** [mkrizmancic/franka_gazebo#1]
Gazebo can't find the materials for meshes and robot becomes invisible

**Comment by mkrizmancic** [comment]
Could you please provide a bit more information, like console output or pictures? Do you get any erros when using launch files? Also, which Gazebo and ROS versions are you running? This package was tested for ROS Kinetic and Gazebo 7.

All the required files are in `meshes` folder and urdf description files should be able to reference them.
As far as I know, there shouldn't be any need for materials since texture data is already encoded in Collada files (.dae) for visual representation of the robot. These files are the original ones from frankaemika's [repository](https://github.com/frankaemika/franka_ros) and should work just fine.

**Comment by skapix** [comment]
Ubuntu 18.04 melodic
Gazebo multi-robot simulator, version 9.0.0
There are no errors, it's just empty
![Screenshot from 2019-03-14 00-01-36](https://user-images.githubusercontent.com/7682569/54320225-83f54b00-45ec-11e9-8f20-7b6f183b23bf.png)
That was just my assumption about materials, maybe I'm wrong

**Comment by mkrizmancic** [comment]
It seems that the Gazebo changed the way it loads meshes and how it reads the `<transparency>` tag in Collada files. I've found [this thread](https://bitbucket.org/osrf/gazebo/issues/2290/mesh-is-invisible-but-i-can-see-it-as-a) describing a similar issue. It looks like the bug has been fixed so I'm not really sure why it's not working for you.

Anyway, I doubt that I'll have spare time to work on this issue very soon. In the meantime, check out [this repository](https://github.com/erdalpekel/panda_simulation). It was built on Ubuntu 18.04 and ROS Melodic and implements the same features (if not more) as my package.

I hope you will find this helpful.

**Comment by skapix** [comment]
Now I understand that's more a Gazebo issue.
Thank you!

**Comment by Favodar** [comment]
As a workaround in Gazebo 9, you can click on "View" and then activate "Collisions" to see the robot. It doesn't show the materials of course, but if the optics don't matter for your project, and you only need to see what the robot is doing, this works.
